### ISSUE TITLE
10.15.5 的HDMI黑屏是不是不行

### ISSUE THREAD

**Issue by cdqrain** [yhl452493373/S200-OpenCore-0.6.0-DW1560#1]
这个小主机用OpenCore的，你是第一个吧，厉害。
10.15.5 的HDMI黑屏是不是不行？

**Comment by yhl452493373** [comment]
HDMI我已经放弃了，现在是直接用mini dp转hdmi或者mini dp转dp。因为我用的4k显示器，hdmi1.4只有30帧。我现在用的sidecar到ipad pro12.9做副屏。
HDMI黑屏你可能可以参考下https://github.com/EngLearnsh/S200H-NUC-Hackintosh/issues/12
