### ISSUE TITLE
打开SecureBootModel不能启动

### ISSUE THREAD

**Issue by frankcui95** [yhl452493373/S200-OpenCore-0.6.0-DW1560#2]
按照你的配置我也把SecureBootModel配置了j174，只能停留在picker界面

**Comment by yhl452493373** [comment]
确保你的机型配置和我一致，另外据店主说S200分两个版本，两个版本的EFI不通用，具体去咨询卖家吧

**Comment by frankcui95** [comment]
这个问题我确认了。至少是在我的s200上面，不干净安装系统的前提下配置opencore的安全启动在bigsur才有效。
