### ISSUE TITLE
有人测试过HDMI吗？

### ISSUE THREAD

**Issue by xanadu314** [yhl452493373/S200-OpenCore-0.6.0-DW1560#3]
有人测试过HDMI吗？

**Comment by yhl452493373** [comment]
hdmi差不多算无解了，个别人能弄成要拔一次才能显示的那种。

对我来说这个HDMI没啥用，因为HDMI是1.4的，4K只有30，因次用不用都无所谓了。

我用的是mini dp转hdmi2.0，扩展功能用的随航，配合12.9的咸鱼二手ipad pro，没啥问题。
