### ISSUE TITLE
S200的HDMI目前无解哈

### ISSUE THREAD

**Issue by yhl452493373** [yhl452493373/S200-OpenCore-0.6.0-DW1560#4]
请用mini dp或者mini dp转hdmi、mini dp转dp的线。线要主动式的。我测试用的是开博尔的mini dp转hdmi和mini dp线连我的15.6的便携显示器，工作正常。

目前来说，这个机型的HDMI是1.4，只能4K30，也不存在多大使用价值。如果确实需要扩展屏，推荐收个二手ipad pro 12.9，通过随航使用。

**Comment by chenyucheng0503** [comment]
请问我使用miniDP开机，之后插入HDMI，可以正常运行吗？（我看 说明.txt 中是可以的）
另外，我使用苹果原装网卡的话，有什么设置需要更改吗
